### PR TITLE
Website rewrite: Part 1

### PR DESCRIPTION
**Pull request by tetraphobia**
:cl:

- Website is a bit more mobile friendly (just a bit, still needs work)
- Layout of the page has changed drastically.
- Removed tg's server banner.
- Added script that will fetch recently closed PRs and display them on the website.
- Doubled the amount of art displayed on the page (200% cultured).
- Changed logo and removed stripes from the navbar (sorry flatty :c)
- Preloader will now be disabled if the client has javascript disabled.

/:cl:

TODO:

- Cache the json retrieved from Github
- Implement round timer, round status, etc under the navbar ala Baystation.
- Change the fonts 10 more times

Before:
image

After:
image
image

### CODE REVIEW

**Review by SamHPurp — APPROVED** [review]
Looks awesome mate

**Comment by SamHPurp** [comment]
My only question is around the 'join' button which appears to be gone in the new version?

**Comment by tetraphobia** [comment]
Good point, I had planned on putting it under the server info near the center of the page. I'll put it on the navbar for now.

**Comment by tetraphobia** [comment]
image

**Comment by SamHPurp** [comment]
Nice thanks. Is this merge-ready for phase 1, or do you have more you're going to add to this tranche?

**Comment by tetraphobia** [comment]
Should be good to merge.

**Comment by SamHPurp** [comment]
Erm. It killed it. 🤔

**Pull request merged**
